export const GET_FOLDERS_SUCCESS = 'GET_FOLDERS_SUCCESS';
export const GET_FOLDERS_ERROR = 'GET_FOLDERS_ERROR';
export const PUT_FOLDER_SUCCESS = 'PUT_FOLDER_SUCCESS';
export const PUT_FOLDER_ERROR = 'PUT_FOLDER_ERROR';
export const POST_FOLDER_SUCCESS = 'POST_FOLDER_SUCCESS';
export const POST_FOLDER_ERROR = 'POST_FOLDER_ERROR';
export const CHANGE_FOLDER_NAME = 'CHANGE_FOLDER_NAME';
export const IS_EDIT_FOLDER = 'IS_EDIT_FOLDER';
export const EDIT_FOLDER = 'CHANGE_EDIT_STATUS';

